import type { TriviaFact } from './ContentCatalog';
import type { QuestionTemplateId } from './QuestionTemplateCatalog';

export interface OrderedFact {
    id: string;
    prompt: string;
    parts: readonly string[];
}

type ExpansionTriviaFact = TriviaFact & { id: string };

export const EXPANSION_TRIVIA_PACKS: Readonly<Partial<Record<QuestionTemplateId, readonly ExpansionTriviaFact[]>>> = {
    'hanzi-radical': [
        { id: 'radical.休', prompt: '“休”的部首', answer: '亻', wrong: ['木', '人', '十'] },
        { id: 'radical.江', prompt: '“江”的部首', answer: '氵', wrong: ['工', '水', '冫'] },
        { id: 'radical.草', prompt: '“草”的部首', answer: '艹', wrong: ['早', '日', '十'] },
        { id: 'radical.晴', prompt: '“晴”的部首', answer: '日', wrong: ['青', '月', '目'] },
        { id: 'radical.跑', prompt: '“跑”的部首', answer: '足', wrong: ['包', '走', '止'] },
        { id: 'radical.妈', prompt: '“妈”的部首', answer: '女', wrong: ['马', '母', '人'] },
        { id: 'radical.桥', prompt: '“桥”的部首', answer: '木', wrong: ['乔', '禾', '朩'] },
        { id: 'radical.海', prompt: '“海”的部首', answer: '氵', wrong: ['每', '水', '母'] },
    ],
    'hanzi-compose': [
        { id: 'compose.林', prompt: '木＋木组成', answer: '林', wrong: ['森', '休', '本'] },
        { id: 'compose.明', prompt: '日＋月组成', answer: '明', wrong: ['朋', '晴', '阳'] },
        { id: 'compose.休', prompt: '亻＋木组成', answer: '休', wrong: ['体', '林', '保'] },
        { id: 'compose.好', prompt: '女＋子组成', answer: '好', wrong: ['妈', '字', '仔'] },
        { id: 'compose.男', prompt: '田＋力组成', answer: '男', wrong: ['苗', '勇', '累'] },
        { id: 'compose.尖', prompt: '小＋大组成', answer: '尖', wrong: ['尘', '太', '少'] },
        { id: 'compose.岩', prompt: '山＋石组成', answer: '岩', wrong: ['岸', '矿', '磊'] },
        { id: 'compose.尘', prompt: '小＋土组成', answer: '尘', wrong: ['尖', '灰', '沙'] },
    ],
    'english-synonym': [
        { id: 'synonym.quick', prompt: 'QUICK的近义词', answer: 'FAST', wrong: ['SLOW', 'LATE', 'QUIET'] },
        { id: 'synonym.large', prompt: 'LARGE的近义词', answer: 'BIG', wrong: ['SMALL', 'THIN', 'SHORT'] },
        { id: 'synonym.small', prompt: 'SMALL的近义词', answer: 'LITTLE', wrong: ['LARGE', 'LONG', 'WIDE'] },
        { id: 'synonym.begin', prompt: 'BEGIN的近义词', answer: 'START', wrong: ['STOP', 'END', 'WAIT'] },
        { id: 'synonym.smart', prompt: 'SMART的近义词', answer: 'CLEVER', wrong: ['SLOW', 'WEAK', 'LOUD'] },
        { id: 'synonym.happy', prompt: 'HAPPY的近义词', answer: 'GLAD', wrong: ['SAD', 'ANGRY', 'TIRED'] },
        { id: 'synonym.quiet', prompt: 'QUIET的近义词', answer: 'SILENT', wrong: ['LOUD', 'FAST', 'BRIGHT'] },
        { id: 'synonym.finish', prompt: 'FINISH的近义词', answer: 'END', wrong: ['BEGIN', 'OPEN', 'ENTER'] },
    ],
    'life-place': [
        { id: 'place.book', prompt: '借阅图书通常去哪里', answer: '图书馆', wrong: ['体育馆', '菜市场', '车站'] },
        { id: 'place.mail', prompt: '寄送包裹通常去哪里', answer: '邮局', wrong: ['药店', '公园', '影院'] },
        { id: 'place.medicine', prompt: '购买常用药通常去哪里', answer: '药店', wrong: ['书店', '银行', '车站'] },
        { id: 'place.train', prompt: '乘坐火车通常去哪里', answer: '火车站', wrong: ['码头', '超市', '医院'] },
        { id: 'place.swim', prompt: '学习游泳通常去哪里', answer: '游泳馆', wrong: ['图书馆', '博物馆', '音乐厅'] },
        { id: 'place.exhibit', prompt: '参观历史文物通常去哪里', answer: '博物馆', wrong: ['体育馆', '邮局', '餐厅'] },
        { id: 'place.deposit', prompt: '办理存款通常去哪里', answer: '银行', wrong: ['学校', '剧院', '公园'] },
        { id: 'place.doctor', prompt: '身体不适需要就诊去哪里', answer: '医院', wrong: ['商场', '车站', '书店'] },
    ],
    'life-public-sign': [
        { id: 'sign.exit', prompt: '“安全出口”标志指向', answer: '疏散出口', wrong: ['收银台', '停车位', '卫生间'] },
        { id: 'sign.no-smoking', prompt: '划掉香烟的标志表示', answer: '禁止吸烟', wrong: ['允许点火', '出售香烟', '注意通风'] },
        { id: 'sign.crosswalk', prompt: '斑马线标志提示', answer: '人行横道', wrong: ['高速入口', '禁止行人', '停车区域'] },
        { id: 'sign.first-aid', prompt: '绿色十字标志通常表示', answer: '急救点', wrong: ['餐饮区', '售票处', '行李处'] },
        { id: 'sign.recycle', prompt: '循环箭头标志通常表示', answer: '可回收', wrong: ['有毒', '易燃', '不可触摸'] },
        { id: 'sign.wet-floor', prompt: '“小心地滑”标志提醒', answer: '地面湿滑', wrong: ['台阶损坏', '高温区域', '车辆经过'] },
        { id: 'sign.no-entry', prompt: '红圈白横杠标志表示', answer: '禁止驶入', wrong: ['直行', '停车', '减速'] },
        { id: 'sign.accessible', prompt: '轮椅图案标志表示', answer: '无障碍设施', wrong: ['儿童区域', '行李寄存', '自行车道'] },
    ],
    'life-safe-behavior': [
        { id: 'safe.fire', prompt: '发现初起火灾应优先', answer: '报警并撤离', wrong: ['乘电梯下楼', '躲进衣柜', '返回取物'] },
        { id: 'safe.road', prompt: '过马路的正确做法', answer: '走人行横道', wrong: ['低头看手机', '翻越护栏', '追逐车辆'] },
        { id: 'safe.electric', prompt: '发现电线破损应当', answer: '远离并求助', wrong: ['徒手触摸', '用水冲洗', '继续使用'] },
        { id: 'safe.gas', prompt: '闻到燃气味应当', answer: '关阀并通风', wrong: ['打开电灯', '点火检查', '使用打火机'] },
        { id: 'safe.storm', prompt: '雷雨时较安全的做法', answer: '进入建筑物内', wrong: ['躲在孤树下', '站在高处', '触摸金属杆'] },
        { id: 'safe.stranger', prompt: '陌生人索要验证码时', answer: '拒绝并核实', wrong: ['立即告知', '转发给朋友', '公开在群里'] },
        { id: 'safe.water', prompt: '不会游泳者落水时同伴应', answer: '呼救找工具', wrong: ['直接跳水', '独自下水', '转身离开'] },
        { id: 'safe.food', prompt: '发现食品过期应当', answer: '停止食用', wrong: ['加热后食用', '继续保存', '掩盖日期'] },
    ],
    'geography-continent': [
        { id: 'continent.china', prompt: '中国位于哪个洲', answer: '亚洲', wrong: ['欧洲', '非洲', '南美洲'] },
        { id: 'continent.france', prompt: '法国位于哪个洲', answer: '欧洲', wrong: ['亚洲', '非洲', '北美洲'] },
        { id: 'continent.egypt', prompt: '埃及主要位于哪个洲', answer: '非洲', wrong: ['欧洲', '亚洲', '南美洲'] },
        { id: 'continent.brazil', prompt: '巴西位于哪个洲', answer: '南美洲', wrong: ['北美洲', '非洲', '欧洲'] },
        { id: 'continent.canada', prompt: '加拿大位于哪个洲', answer: '北美洲', wrong: ['南美洲', '欧洲', '大洋洲'] },
        { id: 'continent.australia', prompt: '澳大利亚位于哪个洲', answer: '大洋洲', wrong: ['亚洲', '欧洲', '非洲'] },
        { id: 'continent.india', prompt: '印度位于哪个洲', answer: '亚洲', wrong: ['欧洲', '非洲', '大洋洲'] },
        { id: 'continent.argentina', prompt: '阿根廷位于哪个洲', answer: '南美洲', wrong: ['北美洲', '亚洲', '欧洲'] },
    ],
    'geography-landmark': [
        { id: 'landmark.great-wall', prompt: '长城位于哪个国家', answer: '中国', wrong: ['日本', '印度', '埃及'] },
        { id: 'landmark.eiffel', prompt: '埃菲尔铁塔位于哪个国家', answer: '法国', wrong: ['英国', '德国', '意大利'] },
        { id: 'landmark.pyramid', prompt: '吉萨金字塔位于哪个国家', answer: '埃及', wrong: ['希腊', '土耳其', '印度'] },
        { id: 'landmark.liberty', prompt: '自由女神像位于哪个国家', answer: '美国', wrong: ['加拿大', '法国', '巴西'] },
        { id: 'landmark.opera', prompt: '悉尼歌剧院位于哪个国家', answer: '澳大利亚', wrong: ['新西兰', '英国', '美国'] },
        { id: 'landmark.colosseum', prompt: '斗兽场位于哪个国家', answer: '意大利', wrong: ['西班牙', '希腊', '法国'] },
        { id: 'landmark.fuji', prompt: '富士山位于哪个国家', answer: '日本', wrong: ['韩国', '中国', '尼泊尔'] },
        { id: 'landmark.taj', prompt: '泰姬陵位于哪个国家', answer: '印度', wrong: ['泰国', '巴基斯坦', '伊朗'] },
    ],
    'geography-province-capital': [
        { id: 'province.guangdong', prompt: '广东省省会', answer: '广州', wrong: ['深圳', '珠海', '佛山'] },
        { id: 'province.sichuan', prompt: '四川省省会', answer: '成都', wrong: ['重庆', '绵阳', '乐山'] },
        { id: 'province.zhejiang', prompt: '浙江省省会', answer: '杭州', wrong: ['宁波', '温州', '绍兴'] },
        { id: 'province.jiangsu', prompt: '江苏省省会', answer: '南京', wrong: ['苏州', '无锡', '徐州'] },
        { id: 'province.hubei', prompt: '湖北省省会', answer: '武汉', wrong: ['宜昌', '襄阳', '荆州'] },
        { id: 'province.hunan', prompt: '湖南省省会', answer: '长沙', wrong: ['株洲', '衡阳', '岳阳'] },
        { id: 'province.shandong', prompt: '山东省省会', answer: '济南', wrong: ['青岛', '烟台', '潍坊'] },
        { id: 'province.fujian', prompt: '福建省省会', answer: '福州', wrong: ['厦门', '泉州', '漳州'] },
    ],
    'geography-relative-position': [
        { id: 'position.japan', prompt: '日本位于中国的大致方向', answer: '东面', wrong: ['西面', '南面', '北面'] },
        { id: 'position.mongolia', prompt: '蒙古位于中国的大致方向', answer: '北面', wrong: ['南面', '东面', '西面'] },
        { id: 'position.india', prompt: '印度位于中国的大致方向', answer: '西南', wrong: ['东北', '正东', '东南'] },
        { id: 'position.russia', prompt: '俄罗斯位于中国的大致方向', answer: '北面', wrong: ['南面', '东南', '西南'] },
        { id: 'position.korea', prompt: '韩国位于中国的大致方向', answer: '东面', wrong: ['西面', '南面', '西北'] },
        { id: 'position.vietnam', prompt: '越南位于中国的大致方向', answer: '南面', wrong: ['北面', '东面', '西北'] },
        { id: 'position.nepal', prompt: '尼泊尔位于中国的大致方向', answer: '西南', wrong: ['东北', '东南', '正东'] },
        { id: 'position.philippines', prompt: '菲律宾位于中国的大致方向', answer: '东南', wrong: ['西北', '东北', '正西'] },
    ],
    'knowledge-astronomy': [
        { id: 'astro.earth-star', prompt: '地球围绕哪颗恒星运行', answer: '太阳', wrong: ['月球', '火星', '北极星'] },
        { id: 'astro.satellite', prompt: '地球的天然卫星', answer: '月球', wrong: ['金星', '太阳', '木星'] },
        { id: 'astro.red', prompt: '常被称为红色星球的是', answer: '火星', wrong: ['金星', '水星', '土星'] },
        { id: 'astro.largest', prompt: '太阳系体积最大的行星', answer: '木星', wrong: ['地球', '火星', '海王星'] },
        { id: 'astro.ring', prompt: '以明显光环著称的行星', answer: '土星', wrong: ['水星', '地球', '火星'] },
        { id: 'astro.day-night', prompt: '昼夜交替主要由什么造成', answer: '地球自转', wrong: ['地球公转', '月球公转', '太阳自转'] },
        { id: 'astro.year', prompt: '一年主要对应地球完成一次', answer: '绕太阳公转', wrong: ['自转', '绕月球公转', '太阳公转'] },
        { id: 'astro.galaxy', prompt: '太阳系所在的星系', answer: '银河系', wrong: ['仙女座星系', '大麦哲伦云', '猎户座'] },
    ],
    'knowledge-biology': [
        { id: 'biology.photosynthesis', prompt: '绿色植物制造有机物主要靠', answer: '光合作用', wrong: ['蒸腾作用', '呼吸作用', '消化作用'] },
        { id: 'biology.breath', prompt: '人体进行气体交换的主要器官', answer: '肺', wrong: ['胃', '肾', '肝'] },
        { id: 'biology.blood', prompt: '推动血液循环的主要器官', answer: '心脏', wrong: ['肺', '胃', '胰腺'] },
        { id: 'biology.plant-water', prompt: '植物吸收水分的主要部位', answer: '根', wrong: ['花', '果实', '种子'] },
        { id: 'biology.bird', prompt: '鸟类身体表面通常覆盖', answer: '羽毛', wrong: ['鳞片', '毛发', '甲壳'] },
        { id: 'biology.fish', prompt: '鱼类主要依靠什么呼吸', answer: '鳃', wrong: ['肺', '皮毛', '气孔'] },
        { id: 'biology.seed', prompt: '种子萌发通常首先需要', answer: '适量水分', wrong: ['强烈阳光', '大量肥料', '低温冰冻'] },
        { id: 'biology.teeth', prompt: '门齿主要用于', answer: '切断食物', wrong: ['磨碎食物', '听声音', '过滤空气'] },
    ],
    'knowledge-physics': [
        { id: 'physics.gravity', prompt: '物体下落主要受到', answer: '重力', wrong: ['浮力', '磁力', '弹力'] },
        { id: 'physics.sound', prompt: '声音不能在什么环境传播', answer: '真空', wrong: ['空气', '水', '钢铁'] },
        { id: 'physics.shadow', prompt: '影子的形成说明光通常', answer: '沿直线传播', wrong: ['只会弯曲', '没有方向', '不能反射'] },
        { id: 'physics.float', prompt: '轮船能浮在水面主要受到', answer: '浮力', wrong: ['磁力', '电力', '摩擦力'] },
        { id: 'physics.friction', prompt: '鞋底花纹主要用于增大', answer: '摩擦力', wrong: ['浮力', '重力', '弹力'] },
        { id: 'physics.lever', prompt: '使用开瓶器体现的简单机械', answer: '杠杆', wrong: ['滑轮', '斜面', '齿轮'] },
        { id: 'physics.reflect', prompt: '平面镜成像利用光的', answer: '反射', wrong: ['吸收', '发声', '导电'] },
        { id: 'physics.conductor', prompt: '下列通常容易导电的是', answer: '铜线', wrong: ['橡皮', '玻璃', '干木块'] },
    ],
    'knowledge-technology': [
        { id: 'tech.cpu', prompt: '计算机中负责运算控制的核心部件', answer: 'CPU', wrong: ['显示器', '键盘', '音箱'] },
        { id: 'tech.qr', prompt: '二维码主要用于', answer: '编码和读取信息', wrong: ['测量温度', '放大声音', '净化空气'] },
        { id: 'tech.gps', prompt: '手机导航定位常使用', answer: '卫星定位', wrong: ['显微镜', '指南针磁化', '声呐捕鱼'] },
        { id: 'tech.wifi', prompt: 'Wi-Fi主要提供', answer: '无线网络连接', wrong: ['食品冷藏', '机械动力', '水质过滤'] },
        { id: 'tech.cloud', prompt: '云存储通常把数据保存在', answer: '远程服务器', wrong: ['纸张', '电池', '扬声器'] },
        { id: 'tech.password', prompt: '更安全的密码做法是', answer: '使用不同的复杂密码', wrong: ['所有网站相同', '告诉陌生人', '只用生日'] },
        { id: 'tech.update', prompt: '及时安装安全更新有助于', answer: '修复已知漏洞', wrong: ['耗尽电池', '删除屏幕', '关闭网络'] },
        { id: 'tech.backup', prompt: '定期备份数据主要为了', answer: '防止意外丢失', wrong: ['降低音量', '加快充电', '改变颜色'] },
    ],
    'history-person-event': [
        { id: 'person.qin', prompt: '统一六国并建立秦朝的人物', answer: '秦始皇', wrong: ['汉武帝', '唐太宗', '宋太祖'] },
        { id: 'person.zhenghe', prompt: '明代率船队七下西洋的人物', answer: '郑和', wrong: ['张骞', '玄奘', '鉴真'] },
        { id: 'person.linzexu', prompt: '主持虎门销烟的人物', answer: '林则徐', wrong: ['魏源', '左宗棠', '曾国藩'] },
        { id: 'person.sun', prompt: '领导辛亥革命的重要人物', answer: '孙中山', wrong: ['康有为', '李鸿章', '林则徐'] },
        { id: 'person.simaqian', prompt: '《史记》的作者', answer: '司马迁', wrong: ['司马光', '班固', '陈寿'] },
        { id: 'person.lishizhen', prompt: '《本草纲目》的作者', answer: '李时珍', wrong: ['张仲景', '华佗', '孙思邈'] },
        { id: 'person.bisheng', prompt: '活字印刷术的发明者', answer: '毕昇', wrong: ['蔡伦', '张衡', '祖冲之'] },
        { id: 'person.zhangqian', prompt: '西汉出使西域的重要人物', answer: '张骞', wrong: ['班超', '郑和', '玄奘'] },
    ],
};

export const EXPANSION_ORDER_PACKS: Readonly<Partial<Record<QuestionTemplateId, readonly OrderedFact[]>>> = {
    'english-word-order': [
        { id: 'sentence.i-like-apples', prompt: '组成英语句子', parts: ['I', 'LIKE', 'APPLES'] },
        { id: 'sentence.she-can-swim', prompt: '组成英语句子', parts: ['SHE', 'CAN', 'SWIM'] },
        { id: 'sentence.this-is-book', prompt: '组成英语句子', parts: ['THIS', 'IS', 'A', 'BOOK'] },
        { id: 'sentence.we-go-school', prompt: '组成英语句子', parts: ['WE', 'GO', 'TO', 'SCHOOL'] },
        { id: 'sentence.bird-can-fly', prompt: '组成英语句子', parts: ['THE', 'BIRD', 'CAN', 'FLY'] },
        { id: 'sentence.he-reads-books', prompt: '组成英语句子', parts: ['HE', 'READS', 'BOOKS'] },
        { id: 'sentence.the-sun-shines', prompt: '组成英语句子', parts: ['THE', 'SUN', 'SHINES'] },
        { id: 'sentence.they-play-football', prompt: '组成英语句子', parts: ['THEY', 'PLAY', 'FOOTBALL'] },
    ],
    'life-process': [
        { id: 'process.handwash', prompt: '洗手顺序', parts: ['打湿双手', '涂洗手液', '揉搓双手', '冲洗擦干'] },
        { id: 'process.toothbrush', prompt: '刷牙顺序', parts: ['挤牙膏', '刷牙齿', '漱口', '清洗牙刷'] },
        { id: 'process.cook-rice', prompt: '电饭锅煮饭顺序', parts: ['量取大米', '淘洗加水', '按下煮饭键', '等待完成'] },
        { id: 'process.mail', prompt: '寄快递顺序', parts: ['包装物品', '填写信息', '交给快递员', '查询物流'] },
        { id: 'process.bus', prompt: '乘公交顺序', parts: ['查看线路', '排队候车', '上车付费', '到站下车'] },
        { id: 'process.library', prompt: '借书顺序', parts: ['查找图书', '取下图书', '办理借阅', '按期归还'] },
        { id: 'process.laundry', prompt: '洗衣顺序', parts: ['分类衣物', '放入洗衣机', '启动洗涤', '取出晾晒'] },
        { id: 'process.recycle', prompt: '投放垃圾顺序', parts: ['确认垃圾种类', '找到对应桶', '分类投放', '清洁双手'] },
    ],
    'history-chronology': [
        { id: 'chronology.dynasty-1', prompt: '按朝代先后排序', parts: ['秦', '汉', '唐', '宋'] },
        { id: 'chronology.dynasty-2', prompt: '按朝代先后排序', parts: ['夏', '商', '周', '秦'] },
        { id: 'chronology.dynasty-3', prompt: '按朝代先后排序', parts: ['隋', '唐', '宋', '元'] },
        { id: 'chronology.modern-1', prompt: '按事件先后排序', parts: ['鸦片战争', '洋务运动', '戊戌变法', '辛亥革命'] },
        { id: 'chronology.modern-2', prompt: '按事件先后排序', parts: ['五四运动', '九一八事变', '七七事变', '抗战胜利'] },
        { id: 'chronology.discovery', prompt: '按发明出现先后排序', parts: ['造纸术', '印刷术', '指南针航海', '蒸汽机'] },
        { id: 'chronology.republic', prompt: '按事件先后排序', parts: ['辛亥革命', '五四运动', '北伐战争', '抗战胜利'] },
        { id: 'chronology.world', prompt: '按时代先后排序', parts: ['古代', '中世纪', '近代', '现代'] },
    ],
};
